/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project.NGO;

/**
 *
 * @author rajen
 */
public class NGO {
 
    private String ngoName;
    private String ngoId;
    private static int count;
    //NGO constructor to autogenerated ids
    public NGO() {
        
        ngoId="ORG"+(++count);
        
    }
    
    public String getNgoId() {
        return ngoId;
    }

    public void setNgoId(String ngoid) {
        this.ngoId = ngoid;
    }
    
    public String getNgoName() {
        return ngoName;
    }

    public void setNgoName(String Name) {
        this.ngoName = Name;
    }
    
    @Override
    public String toString(){
        
        return ngoName;
    }
    
    
}